<HTML>
<HEAD>
<meta charset="UTF-8">
<title>ClientResources.CallbackListener.onError - foundation</title>
<link rel="stylesheet" href="../../../../style.css">
</HEAD>
<BODY>
<a href="../../../index.html">foundation</a>&nbsp;/&nbsp;<a href="../../index.html">com.sap.cloud.mobile.foundation.clientresources</a>&nbsp;/&nbsp;<a href="../index.html">ClientResources</a>&nbsp;/&nbsp;<a href="index.html">CallbackListener</a>&nbsp;/&nbsp;<a href="./onerror.html">onError</a><br/>
<br/>
<h1>onError</h1>
<a name="com.sap.cloud.mobile.foundation.clientresources.ClientResources.CallbackListener$onError(kotlin.Throwable)"></a>
<code><span class="keyword">abstract</span> <span class="keyword">fun </span><span class="identifier">onError</span><span class="symbol">(</span><span class="identifier">@NonNull</span> <span class="identifier" id="com.sap.cloud.mobile.foundation.clientresources.ClientResources.CallbackListener$onError(kotlin.Throwable)/error">error</span><span class="symbol">:</span>&nbsp;<span class="identifier">Throwable</span><span class="symbol">)</span><span class="symbol">: </span><span class="identifier">Unit</span></code>
<p>This method is invoked in the UI thread when the operation failed to complete successfully with one of the following errors: </p>
<p>1. <code><a href="#">Exception</a></code>-- error returned from CPMS server. </p>
<p>2. <code><a href="#">IOException</a></code>-- when operation is cancelled or encountered network occurred.</p>
<h3>Parameters</h3>
<p><a name="error"></a>
<code>error</code> - <span class="identifier">Throwable</span><span class="symbol">:</span> the error that occurred.</p>
<a name="com.sap.cloud.mobile.foundation.clientresources.ClientResources.CallbackListener$onError(kotlin.Throwable)"></a>
<code><span class="keyword">abstract</span> <span class="keyword">fun </span><span class="identifier">onError</span><span class="symbol">(</span><span class="identifier">@NonNull</span> <span class="identifier" id="com.sap.cloud.mobile.foundation.clientresources.ClientResources.CallbackListener$onError(kotlin.Throwable)/error">error</span><span class="symbol">:</span>&nbsp;<span class="identifier">Throwable</span><span class="symbol">)</span><span class="symbol">: </span><span class="identifier">Unit</span></code>
<p>This method is invoked in the UI thread when the operation failed to complete successfully with one of the following errors: </p>
<p>1. <code><a href="#">Exception</a></code>-- error returned from CPMS server. </p>
<p>2. <code><a href="#">IOException</a></code>-- when operation is cancelled or encountered network occurred.</p>
<h3>Parameters</h3>
<p><a name="error"></a>
<code>error</code> - <span class="identifier">Throwable</span><span class="symbol">:</span> the error that occurred.</p>
</BODY>
</HTML>
